### ISSUE TITLE
cannot running when  docker-compose -f mariadb-cluster-setup-v3.yaml up -d

### ISSUE THREAD

**Issue by igstbagusdharmaputra** [ustcweizhou/mariadb-cluster#1]
"/init.sh"      24 seconds ago   Exited (134) 22 seconds ago    docker-mariadb-cluster_db01_1
  "/init.sh"      24 seconds ago   Exited (1)  22 seconds ago    docker-mariadb-cluster_db01_2
  "/init.sh"      24 seconds ago   Exited  (1)  22 seconds ago    docker-mariadb-cluster_db01_3

**Comment by weizhouapache** [comment]
@igstbagusdharmaputra 
thanks for reporting this issue.
the image version in mariadb-cluster-setup-v3.yaml is 'ubuntu18-10.4' which is out-of-date.
could you please change version to 'latest' and retry ? see #2

**Comment by igstbagusdharmaputra** [comment]
> @igstbagusdharmaputra
> thanks for reporting this issue.
> the image version in mariadb-cluster-setup-v3.yaml is 'ubuntu18-10.4' which is out-of-date.
> could you please change version to 'latest' and retry ? see #2

I've replaced the image ubuntu latest version, but it's the same as before cannot running
