### ISSUE TITLE
 Exited (134) 14 seconds ago docker-mariadb-cluster_db01_1

### ISSUE THREAD

**Issue by igstbagusdharmaputra** [ustcweizhou/mariadb-cluster#3]
![Screenshot_7](https://user-images.githubusercontent.com/42177839/104558132-48f74f00-567d-11eb-83da-9b6fe426a319.png)

**Comment by weizhouapache** [comment]
@igstbagusdharmaputra  do you still have issue ?
if yes, could you provide more information ?
1. you OS and version
2. docker-compose version
3. docker image ID. 
```
# docker image ls |grep mariadb-cluster
ustcweizhou/mariadb-cluster   latest              b1b7cf38c330        2 days ago          478MB
```
4. logs on db01/02/03
```
# docker-compose -f mariadb-cluster-setup-v3.yaml logs db01
....
db01_1   | 2021-01-14  6:15:12 0 [Note] WSREP: Donor monitor thread ended with total time 13 sec
db01_1   | 2021-01-14  6:15:14 0 [Note] WSREP: async IST sender served
db01_1   | 2021-01-14  6:15:14 0 [Note] WSREP: 1.0 (db02): State transfer from 0.0 (db01) complete.
db01_1   | 2021-01-14  6:15:14 0 [Note] WSREP: Member 1.0 (db02) synced with group.
```


it works on my server.
![image](https://user-images.githubusercontent.com/57355700/104558683-78896580-5643-11eb-844e-22af6de733e7.png)

**Comment by igstbagusdharmaputra** [comment]
I am use ubuntu server 18.04
![Screenshot_1](https://user-images.githubusercontent.com/42177839/104559742-cfad2b80-567f-11eb-8ffa-9727fb062651.png)
![Screenshot_2](https://user-images.githubusercontent.com/42177839/104559744-d0de5880-567f-11eb-8bdc-c22949066ec3.png)

**Comment by weizhouapache** [comment]
@igstbagusdharmaputra
It looks there are still old data created with mariadb 10.4.13 in data dir.

if you use it for testing, you can retry after removing all containers (and all data !!) by ` docker-compose -f mariadb-cluster-setup-v3.yaml down `
